---
title: "Análise do SMOTE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)

datasets <- c('10797', '38959', '45827', '53752', '57297', '62944', '70947', '71053', '7904')
classifier <- c("svmRadial", "J48", "knn", "nnet", "OneR")
project_path <- "~/Documents/codelab.nosync/biomarker_id/"
results_path <- paste(project_path, "results/training/", sep = "")
data_path <- paste(project_path, "data/processed/train/", sep = "")

source(paste(project_path, "scripts/utils/train.R", sep = ""))
```

## Performance s/ SMOTE com 5 genes selecionados
```{r echo=FALSE}
results <- list()
i <- 1

for(code in datasets) {
  filepath <- paste(data_path, "GSE", code, "_common.rda", sep = "")
  load(filepath)
  
  trainI <- readRDS(paste(results_path, "GSE", code, "_common/trainI.rds", sep = ""))
  mean <- readRDS(paste(results_path, "GSE", code, "_common/final_rankings/mean.rds", sep = ""))
  
  ranking <- mean[["mRMR"]][["200"]]
  top5_features <- ranking[c(1:5), 1]
  
  validationI <- setdiff(1:nrow(x), trainI)
  
  validationX <- x[validationI, ]
  validationY <- y[validationI]
  
  path <- paste(project_path, "reports/smote_analysis/GSE", code, "_results.rds", sep = "")
  recalls <- readRDS(path)  # list()
  for(classif in classifier) {
    # model <- trainModel(validationX[, top5_features], validationY, getLOOCV(), classif)
    no_smote_recall <- recalls[[classif]]  # max(model[["results"]][["Sens"]])
    
    smote_model <- readRDS(paste(results_path, "GSE", code, "_common/models/", classif, ".rds", sep = ""))
    smote_recall <- max(smote_model[["mean"]][["mRMR"]][["200"]][["5"]][["metrics"]][["Recall"]])
    
    results[[i]] <- c(paste("GSE", code, sep = ""), classif, "No", no_smote_recall)
    results[[i + 1]] <- c(paste("GSE", code, sep = ""), classif, "Yes", smote_recall)
    
    i <- i + 2
  }
  
  # saveRDS(recalls, path)
}

results <- t(data.frame(results, row.names = c("Dataset", "Classifier", "SMOTE", "Recall")))
results <- data.frame(results)

svmRadial <- results %>% filter(Classifier == "svmRadial")
ggplot(svmRadial, aes(Dataset, Recall, color = SMOTE)) + geom_point() + theme(axis.text.x = element_text(angle = 90))
```

## Performance s/ SMOTE com 5 genes aleatórios
```{r echo=FALSE}
results_r <- list()
i <- 1

for(code in datasets) {
  filepath <- paste(data_path, "GSE", code, "_common.rda", sep = "")
  load(filepath)
  
  trainI <- readRDS(paste(results_path, "GSE", code, "_common/trainI.rds", sep = ""))
  features <- sample(names(x), 5)
  
  validationI <- setdiff(1:nrow(x), trainI)
  
  validationX <- x[validationI, ]
  validationY <- y[validationI]
  
  path <- paste(project_path, "reports/smote_analysis/GSE", code, "_results_r.rds", sep = "")
  recalls <- list() # readRDS(path)
  for(classif in classifier) {
    no_smote_recall <- 0
    
    for(j in 1:10) {
      features <- sample(names(x), 5)
      model <- trainModel(validationX[, features], validationY, getLOOCV(), classif)
      no_smote_recall <- max(model[["results"]][["Sens"]]) + no_smote_recall # recalls[[classif]]
    }
    
    recalls[[classif]] <- no_smote_recall / 10
    
    smote_model <- readRDS(paste(results_path, "GSE", code, "_common/models/", classif, ".rds", sep = ""))
    smote_recall <- max(smote_model[["mean"]][["mRMR"]][["200"]][["5"]][["metrics"]][["Recall"]])
    
    results_r[[i]] <- c(paste("GSE", code, sep = ""), classif, "No", recalls[[classif]])
    results_r[[i + 1]] <- c(paste("GSE", code, sep = ""), classif, "Yes", smote_recall)
    
    i <- i + 2
  }
  
  saveRDS(recalls, path)
}

results_r <- t(data.frame(results_r, row.names = c("Dataset", "Classifier", "SMOTE", "Recall")))
results_r <- data.frame(results)

svmRadial <- results_r %>% filter(Classifier == "svmRadial")
ggplot(svmRadial, aes(Dataset, Recall, color = SMOTE)) + geom_point() + theme(axis.text.x = element_text(angle = 90)) + scale_y_continuous()
```

